walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1747298473235341
  g: -9.8
  kd:
  - 33.49402483662636
  - 42.49402483662636
  - 33.49402483662636
  - 33.49402483662636
  - 42.49402483662636
  - 33.49402483662636
  kd_torso: 260.35227241477025
  kp:
  - 334.9402483662636
  - 424.9402483662636
  - 334.9402483662636
  - 334.9402483662636
  - 424.9402483662636
  - 334.9402483662636
  kp_torso: 531.9352000678654
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.059041707314265834
    - 0.6226930942176403
    - -1.1635202111505343
    - 0.02278240569153661
    - 0.00495622488171921
    - 0.3503685166301221
    - 0.44069386531683324
  - - -0.021979535195915355
    - -1.4129932771898726
    - -0.7145805983990978
    - -0.21593421360085785
    - -0.009341037910078632
    - -0.33289153324599297
    - 0.6914709622042917
  - - 0.059041707314265834
    - 0.00495622488171921
    - 0.3503685166301221
    - 0.44069386531683324
    - 0.6226930942176403
    - -1.1635202111505343
    - 0.02278240569153661
  - - -0.021979535195915355
    - -0.009341037910078632
    - -0.33289153324599297
    - 0.6914709622042917
    - -1.4129932771898726
    - -0.7145805983990978
    - -0.21593421360085785
