walk:
  c_d: 1.6
  c_v: 0
  dt: 0.17604794340896554
  g: -9.8
  kd:
  - 31.20575801870104
  - 40.20575801870104
  - 31.20575801870104
  - 31.20575801870104
  - 40.20575801870104
  - 31.20575801870104
  kd_torso: 250.40359299635725
  kp:
  - 312.0575801870104
  - 402.0575801870104
  - 312.0575801870104
  - 312.0575801870104
  - 402.0575801870104
  - 312.0575801870104
  kp_torso: 488.4557717764013
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.008701896991419437
    - 0.8995692306753894
    - -1.169177860997497
    - 0.1276078899455282
    - 0.03648243356463363
    - 0.2360868475621177
    - 0.39197544783166355
  - - 0.04918366615726812
    - -1.415452277905896
    - -0.2527250998968744
    - -0.03884814655127059
    - -0.030794321327438562
    - -0.22307219723737803
    - 0.03987357466504353
  - - -0.008701896991419437
    - 0.03648243356463363
    - 0.2360868475621177
    - 0.39197544783166355
    - 0.8995692306753894
    - -1.169177860997497
    - 0.1276078899455282
  - - 0.04918366615726812
    - -0.030794321327438562
    - -0.22307219723737803
    - 0.03987357466504353
    - -1.415452277905896
    - -0.2527250998968744
    - -0.03884814655127059
