walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2937833066750207
  g: -9.8
  kd:
  - 27.67866683577587
  - 36.67866683577587
  - 27.67866683577587
  - 27.67866683577587
  - 36.67866683577587
  - 27.67866683577587
  kd_torso: 234.52817755603076
  kp:
  - 276.7866683577587
  - 366.7866683577587
  - 276.7866683577587
  - 276.7866683577587
  - 366.7866683577587
  - 276.7866683577587
  kp_torso: 479.53131702028844
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.018099188710491605
    - 0.9460508025614723
    - -1.1266208368522763
    - 0.2419196656289564
    - 0.002956762441545577
    - 0.18658662088476394
    - 0.18190888028317492
  - - 0.005155969965690271
    - -1.3242701297164714
    - -0.027993865727593797
    - 0.2654228910418198
    - -0.03187364625638686
    - 0.03840583604838821
    - 0.3112180366826113
  - - 0.018099188710491605
    - 0.002956762441545577
    - 0.18658662088476394
    - 0.18190888028317492
    - 0.9460508025614723
    - -1.1266208368522763
    - 0.2419196656289564
  - - 0.005155969965690271
    - -0.03187364625638686
    - 0.03840583604838821
    - 0.3112180366826113
    - -1.3242701297164714
    - -0.027993865727593797
    - 0.2654228910418198
