walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2151536536396988
  g: -9.8
  kd:
  - 32.147550488393904
  - 41.147550488393904
  - 32.147550488393904
  - 32.147550488393904
  - 41.147550488393904
  - 32.147550488393904
  kd_torso: 262.1552308464083
  kp:
  - 321.47550488393904
  - 411.47550488393904
  - 321.47550488393904
  - 321.47550488393904
  - 411.47550488393904
  - 321.47550488393904
  kp_torso: 531.0533355759959
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.05572572181228325
    - 0.7199965588230627
    - -1.1254247006420446
    - 0.16437987079862415
    - 0.012901610980613485
    - 0.352112030135219
    - 0.43188908617366817
  - - 0.07497463625490443
    - -1.4398646286260124
    - -0.7121245251052387
    - -0.2331996002815464
    - 0.038164764076910454
    - -0.29966427531943596
    - 0.4304407664535839
  - - 0.05572572181228325
    - 0.012901610980613485
    - 0.352112030135219
    - 0.43188908617366817
    - 0.7199965588230627
    - -1.1254247006420446
    - 0.16437987079862415
  - - 0.07497463625490443
    - 0.038164764076910454
    - -0.29966427531943596
    - 0.4304407664535839
    - -1.4398646286260124
    - -0.7121245251052387
    - -0.2331996002815464
