walk:
  c_d: 1.6
  c_v: 0
  dt: 0.14094041316035577
  g: -9.8
  kd:
  - 32.81238256047612
  - 41.812382560476124
  - 32.81238256047612
  - 32.81238256047612
  - 41.812382560476124
  - 32.81238256047612
  kd_torso: 260.9734698079253
  kp:
  - 328.1238256047612
  - 418.1238256047612
  - 328.1238256047612
  - 328.1238256047612
  - 418.1238256047612
  - 328.1238256047612
  kp_torso: 514.5634589771278
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0680967649801477
    - 0.6702972479119947
    - -1.3319885467425867
    - 0.2692850097762166
    - 0.0636404626117513
    - 0.33696759008621024
    - 0.3288284974959028
  - - -0.015348668092874128
    - -1.4215722864134253
    - -0.47046144174646104
    - -0.27618823175541674
    - -0.03114335639848452
    - -0.20410944701601258
    - 0.20924754204937196
  - - 0.0680967649801477
    - 0.0636404626117513
    - 0.33696759008621024
    - 0.3288284974959028
    - 0.6702972479119947
    - -1.3319885467425867
    - 0.2692850097762166
  - - -0.015348668092874128
    - -0.03114335639848452
    - -0.20410944701601258
    - 0.20924754204937196
    - -1.4215722864134253
    - -0.47046144174646104
    - -0.27618823175541674
