walk:
  c_d: 1.6
  c_v: 0
  dt: 0.19094041316035576
  g: -9.8
  kd:
  - 33.20570899791661
  - 42.20570899791661
  - 33.20570899791661
  - 33.20570899791661
  - 42.20570899791661
  - 33.20570899791661
  kd_torso: 260.78378033474917
  kp:
  - 332.05708997916605
  - 422.05708997916605
  - 332.05708997916605
  - 332.05708997916605
  - 422.05708997916605
  - 332.05708997916605
  kp_torso: 520.7659106652771
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0849723481486739
    - 0.6610368403460326
    - -1.2893790136671308
    - 0.229700634180554
    - 0.06202451688149423
    - 0.3689852504090973
    - 0.3198919693499101
  - - 0.003006732016043069
    - -1.4126108704860572
    - -0.4902541375322286
    - -0.21474644947984914
    - -0.0018968947317615052
    - -0.19121716479827122
    - 0.2181607524762977
  - - 0.0849723481486739
    - 0.06202451688149423
    - 0.3689852504090973
    - 0.3198919693499101
    - 0.6610368403460326
    - -1.2893790136671308
    - 0.229700634180554
  - - 0.003006732016043069
    - -0.0018968947317615052
    - -0.19121716479827122
    - 0.2181607524762977
    - -1.4126108704860572
    - -0.4902541375322286
    - -0.21474644947984914
