walk:
  c_d: 1.6
  c_v: 0
  dt: 0.259591379590806
  g: -9.8
  kd:
  - 30.14603023499842
  - 39.14603023499842
  - 30.14603023499842
  - 30.14603023499842
  - 39.14603023499842
  - 30.14603023499842
  kd_torso: 206.92494023310533
  kp:
  - 301.4603023499842
  - 391.4603023499842
  - 301.4603023499842
  - 301.4603023499842
  - 391.4603023499842
  - 301.4603023499842
  kp_torso: 475.1584637587796
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.06617676203838799
    - 0.4816279226569318
    - -1.0065496569813668
    - 0.4239398626482797
    - -0.059791971873417796
    - 0.3922411949141573
    - -0.01751380701341034
  - - -0.2636256179097692
    - -0.8534760299288835
    - 0.06328321132956649
    - 0.4431185178998458
    - 0.031209489609626162
    - 0.0598978489302919
    - 0.27409323408155056
  - - 0.06617676203838799
    - -0.059791971873417796
    - 0.3922411949141573
    - -0.01751380701341034
    - 0.4816279226569318
    - -1.0065496569813668
    - 0.4239398626482797
  - - -0.2636256179097692
    - 0.031209489609626162
    - 0.0598978489302919
    - 0.27409323408155056
    - -0.8534760299288835
    - 0.06328321132956649
    - 0.4431185178998458
