walk:
  c_d: 1.6
  c_v: 0
  dt: 0.3368587576389639
  g: -9.8
  kd:
  - 31.15757996724973
  - 40.15757996724973
  - 31.15757996724973
  - 31.15757996724973
  - 40.15757996724973
  - 31.15757996724973
  kd_torso: 222.10300036044134
  kp:
  - 311.5757996724973
  - 401.5757996724973
  - 311.5757996724973
  - 311.5757996724973
  - 401.5757996724973
  - 311.5757996724973
  kp_torso: 481.0251984774547
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.02418354072834929
    - 0.4523865858065133
    - -0.7296910584159269
    - 0.5516906095688501
    - 0.09573119209320996
    - 0.45935633900538936
    - -0.19098570113008922
  - - -0.17948111091066607
    - -0.841193308030569
    - -0.06821462414281675
    - 0.4591862363948229
    - 0.023590436245241726
    - 0.05705224798835676
    - 0.3500596073675222
  - - 0.02418354072834929
    - 0.09573119209320996
    - 0.45935633900538936
    - -0.19098570113008922
    - 0.4523865858065133
    - -0.7296910584159269
    - 0.5516906095688501
  - - -0.17948111091066607
    - 0.023590436245241726
    - 0.05705224798835676
    - 0.3500596073675222
    - -0.841193308030569
    - -0.06821462414281675
    - 0.4591862363948229
