walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1938837584745536
  g: -9.8
  kd:
  - 33.26415815693314
  - 42.26415815693314
  - 33.26415815693314
  - 33.26415815693314
  - 42.26415815693314
  - 33.26415815693314
  kd_torso: 263.8111347144497
  kp:
  - 332.6415815693314
  - 422.6415815693314
  - 332.6415815693314
  - 332.6415815693314
  - 422.6415815693314
  - 332.6415815693314
  kp_torso: 518.3405783248538
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03391925620654661
    - 0.7632890154197027
    - -1.0941691956967192
    - 0.24301329582991063
    - 0.08226661954585002
    - 0.33551258208780654
    - 0.40172931873652423
  - - -0.003393383699020411
    - -1.4017636419459272
    - -0.588679492680781
    - -0.27157886282313526
    - 0.05111645732729436
    - -0.35247104295533915
    - 0.39718449309802695
  - - 0.03391925620654661
    - 0.08226661954585002
    - 0.33551258208780654
    - 0.40172931873652423
    - 0.7632890154197027
    - -1.0941691956967192
    - 0.24301329582991063
  - - -0.003393383699020411
    - 0.05111645732729436
    - -0.35247104295533915
    - 0.39718449309802695
    - -1.4017636419459272
    - -0.588679492680781
    - -0.27157886282313526
