walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24621086089959418
  g: -9.8
  kd:
  - 30.318864180272488
  - 39.31886418027249
  - 30.318864180272488
  - 30.318864180272488
  - 39.31886418027249
  - 30.318864180272488
  kd_torso: 208.35500269124068
  kp:
  - 303.1886418027249
  - 393.1886418027249
  - 303.1886418027249
  - 303.1886418027249
  - 393.1886418027249
  - 303.1886418027249
  kp_torso: 459.5972623959352
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.006129722209199603
    - 0.457538902601781
    - -0.4238415789417552
    - 0.5122234757787674
    - 0.05352096431684526
    - 0.39007369841017536
    - 0.06202101347404096
  - - -0.3
    - -0.6569991216032365
    - -0.42089503498302155
    - 0.16462307597992995
    - -0.04291096093510633
    - -0.09102314918660831
    - 0.505793181807191
  - - -0.006129722209199603
    - 0.05352096431684526
    - 0.39007369841017536
    - 0.06202101347404096
    - 0.457538902601781
    - -0.4238415789417552
    - 0.5122234757787674
  - - -0.3
    - -0.04291096093510633
    - -0.09102314918660831
    - 0.505793181807191
    - -0.6569991216032365
    - -0.42089503498302155
    - 0.16462307597992995
