walk:
  c_d: 1.6
  c_v: 0
  dt: 0.18057371895308633
  g: -9.8
  kd:
  - 32.03893733052327
  - 41.03893733052327
  - 32.03893733052327
  - 32.03893733052327
  - 41.03893733052327
  - 32.03893733052327
  kd_torso: 262.54924849329115
  kp:
  - 320.38937330523265
  - 410.38937330523265
  - 320.38937330523265
  - 320.38937330523265
  - 410.38937330523265
  - 320.38937330523265
  kp_torso: 502.0672838047473
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.07632521751538335
    - 0.6961199373735355
    - -1.3223394746084824
    - 0.24104863365003376
    - 0.0045533267710803765
    - 0.3347995698589971
    - 0.3758048193970413
  - - -0.08287714691724699
    - -1.4267949737362655
    - -0.42359967199814247
    - -0.2660056321641433
    - -0.0651616416264995
    - -0.27537941492774864
    - 0.048047443021551034
  - - 0.07632521751538335
    - 0.0045533267710803765
    - 0.3347995698589971
    - 0.3758048193970413
    - 0.6961199373735355
    - -1.3223394746084824
    - 0.24104863365003376
  - - -0.08287714691724699
    - -0.0651616416264995
    - -0.27537941492774864
    - 0.048047443021551034
    - -1.4267949737362655
    - -0.42359967199814247
    - -0.2660056321641433
