walk:
  c_d: 1.6
  c_v: 0
  dt: 0.21720660156209742
  g: -9.8
  kd:
  - 30.056014910156694
  - 39.0560149101567
  - 30.056014910156694
  - 30.056014910156694
  - 39.0560149101567
  - 30.056014910156694
  kd_torso: 210.95982348390456
  kp:
  - 300.56014910156694
  - 390.56014910156694
  - 300.56014910156694
  - 300.56014910156694
  - 390.56014910156694
  - 300.56014910156694
  kp_torso: 472.1033599765759
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.06893343816508143
    - 0.5418797800456419
    - -1.0294806808478054
    - 0.4148527221970816
    - 0.007960270052795829
    - 0.3026469312892085
    - 0.06626488437021763
  - - -0.3
    - -0.9587720178153829
    - -0.023074125476954338
    - 0.48318494511024
    - 0.02137927172550725
    - -0.07063648733316534
    - 0.21748474155058323
  - - 0.06893343816508143
    - 0.007960270052795829
    - 0.3026469312892085
    - 0.06626488437021763
    - 0.5418797800456419
    - -1.0294806808478054
    - 0.4148527221970816
  - - -0.3
    - 0.02137927172550725
    - -0.07063648733316534
    - 0.21748474155058323
    - -0.9587720178153829
    - -0.023074125476954338
    - 0.48318494511024
