walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24477104815085643
  g: -9.8
  kd:
  - 29.987125372019836
  - 38.98712537201984
  - 29.987125372019836
  - 29.987125372019836
  - 38.98712537201984
  - 29.987125372019836
  kd_torso: 205.797324325121
  kp:
  - 299.87125372019835
  - 389.87125372019835
  - 299.87125372019835
  - 299.87125372019835
  - 389.87125372019835
  - 299.87125372019835
  kp_torso: 472.53545391878265
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0713161978177782
    - 0.5680988908268809
    - -1.0717054293467139
    - 0.4086341510006493
    - -0.06713007002759015
    - 0.2794462772809952
    - 0.06293003214861198
  - - -0.2403852578384489
    - -1.0819557385522092
    - 0.04685992517521763
    - 0.465163301958856
    - 0.004620823447493792
    - -0.04043132906436114
    - 0.056372029767457324
  - - 0.0713161978177782
    - -0.06713007002759015
    - 0.2794462772809952
    - 0.06293003214861198
    - 0.5680988908268809
    - -1.0717054293467139
    - 0.4086341510006493
  - - -0.2403852578384489
    - 0.004620823447493792
    - -0.04043132906436114
    - 0.056372029767457324
    - -1.0819557385522092
    - 0.04685992517521763
    - 0.465163301958856
