walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24394876563272033
  g: -9.8
  kd:
  - 30.009018077532343
  - 39.009018077532346
  - 30.009018077532343
  - 30.009018077532343
  - 39.009018077532346
  - 30.009018077532343
  kd_torso: 230.14857722150296
  kp:
  - 300.0901807753234
  - 390.0901807753234
  - 300.0901807753234
  - 300.0901807753234
  - 390.0901807753234
  - 300.0901807753234
  kp_torso: 476.16816023252045
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.02562489233530086
    - 0.5306036500263136
    - -0.7960203679436348
    - 0.6134717016845949
    - 0.007390525459158056
    - 0.43087558542223386
    - -0.05934832188972029
  - - -0.20035747650519364
    - -0.6230995541190116
    - -0.20347630662322794
    - 0.5287887014986649
    - 0.03667420414762139
    - 0.015185183239159895
    - 0.5990995305595156
  - - 0.02562489233530086
    - 0.007390525459158056
    - 0.43087558542223386
    - -0.05934832188972029
    - 0.5306036500263136
    - -0.7960203679436348
    - 0.6134717016845949
  - - -0.20035747650519364
    - 0.03667420414762139
    - 0.015185183239159895
    - 0.5990995305595156
    - -0.6230995541190116
    - -0.20347630662322794
    - 0.5287887014986649
