walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2096225774818707
  g: -9.8
  kd:
  - 33.40756386051109
  - 42.40756386051109
  - 33.40756386051109
  - 33.40756386051109
  - 42.40756386051109
  - 33.40756386051109
  kd_torso: 258.3387544387173
  kp:
  - 334.0756386051109
  - 424.0756386051109
  - 334.0756386051109
  - 334.0756386051109
  - 424.0756386051109
  - 334.0756386051109
  kp_torso: 529.7631744779345
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.057368277392243996
    - 0.7772319058332786
    - -1.147753695697304
    - 0.15287627863893893
    - 0.03843898928279693
    - 0.33501698378343375
    - 0.5288402644288271
  - - -0.014082406761638286
    - -1.3949351126976792
    - -0.6356034797277564
    - -0.26677901833104756
    - -0.08150911422575277
    - -0.33266069362479345
    - 0.39683195658675857
  - - 0.057368277392243996
    - 0.03843898928279693
    - 0.33501698378343375
    - 0.5288402644288271
    - 0.7772319058332786
    - -1.147753695697304
    - 0.15287627863893893
  - - -0.014082406761638286
    - -0.08150911422575277
    - -0.33266069362479345
    - 0.39683195658675857
    - -1.3949351126976792
    - -0.6356034797277564
    - -0.26677901833104756
