walk:
  c_d: 1.6
  c_v: 0
  dt: 0.25979213696449727
  g: -9.8
  kd:
  - 29.44707293893093
  - 38.44707293893093
  - 29.44707293893093
  - 29.44707293893093
  - 38.44707293893093
  - 29.44707293893093
  kd_torso: 228.39417709108227
  kp:
  - 294.47072938930927
  - 384.47072938930927
  - 294.47072938930927
  - 294.47072938930927
  - 384.47072938930927
  - 294.47072938930927
  kp_torso: 480.7375893615738
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.035117551854407986
    - 0.7906264187338653
    - -1.0676729281085302
    - 0.35591999991533574
    - -0.00044932750380630507
    - 0.2069018240158507
    - 0.045969542890287596
  - - -0.02840771360552051
    - -1.337506751681198
    - -0.0954985137125765
    - 0.4365758558769093
    - -0.05153294330377054
    - -0.018438980428512046
    - 0.33232939254251226
  - - 0.035117551854407986
    - -0.00044932750380630507
    - 0.2069018240158507
    - 0.045969542890287596
    - 0.7906264187338653
    - -1.0676729281085302
    - 0.35591999991533574
  - - -0.02840771360552051
    - -0.05153294330377054
    - -0.018438980428512046
    - 0.33232939254251226
    - -1.337506751681198
    - -0.0954985137125765
    - 0.4365758558769093
