walk:
  c_d: 1.6
  c_v: 0
  dt: 0.17141587901016297
  g: -9.8
  kd:
  - 30.607176762440346
  - 39.607176762440346
  - 30.607176762440346
  - 30.607176762440346
  - 39.607176762440346
  - 30.607176762440346
  kd_torso: 250.23924965101298
  kp:
  - 306.07176762440344
  - 396.07176762440344
  - 306.07176762440344
  - 306.07176762440344
  - 396.07176762440344
  - 306.07176762440344
  kp_torso: 480.97711780083864
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.033244568180844196
    - 0.8881202966589393
    - -1.2011880922179383
    - 0.18298170658278734
    - -0.014366179950705492
    - 0.14720026079809412
    - 0.09149038005771273
  - - 0.07655968043201142
    - -1.320854580183159
    - -0.10598452119481915
    - 0.12269022828083018
    - -0.03857724115503783
    - -0.14814733539172756
    - 0.06995303544474941
  - - -0.033244568180844196
    - -0.014366179950705492
    - 0.14720026079809412
    - 0.09149038005771273
    - 0.8881202966589393
    - -1.2011880922179383
    - 0.18298170658278734
  - - 0.07655968043201142
    - -0.03857724115503783
    - -0.14814733539172756
    - 0.06995303544474941
    - -1.320854580183159
    - -0.10598452119481915
    - 0.12269022828083018
