walk:
  c_d: 1.6
  c_v: 0
  dt: 0.25509191165560086
  g: -9.8
  kd:
  - 29.45279443074115
  - 38.45279443074115
  - 29.45279443074115
  - 29.45279443074115
  - 38.45279443074115
  - 29.45279443074115
  kd_torso: 203.80399127214272
  kp:
  - 294.5279443074115
  - 384.5279443074115
  - 294.5279443074115
  - 294.5279443074115
  - 384.5279443074115
  - 294.5279443074115
  kp_torso: 481.13766094612134
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.07295611187560692
    - 0.5008458483127377
    - -1.0380771279701912
    - 0.4623649092103631
    - 0.02821282894509991
    - 0.38038938976747877
    - -0.002980828053977612
  - - -0.3
    - -0.9271275994587039
    - 0.03717066802344773
    - 0.4164987560884213
    - -0.07991596530102901
    - -0.008553052146971052
    - 0.21566706150828982
  - - 0.07295611187560692
    - 0.02821282894509991
    - 0.38038938976747877
    - -0.002980828053977612
    - 0.5008458483127377
    - -1.0380771279701912
    - 0.4623649092103631
  - - -0.3
    - -0.07991596530102901
    - -0.008553052146971052
    - 0.21566706150828982
    - -0.9271275994587039
    - 0.03717066802344773
    - 0.4164987560884213
