walk:
  c_d: 1.6
  c_v: 0
  dt: 0.25433306503728104
  g: -9.8
  kd:
  - 34.10725498300072
  - 43.10725498300073
  - 34.10725498300072
  - 34.10725498300072
  - 43.10725498300073
  - 34.10725498300072
  kd_torso: 264.4321752423951
  kp:
  - 341.07254983000723
  - 431.07254983000723
  - 341.07254983000723
  - 341.07254983000723
  - 431.07254983000723
  - 341.07254983000723
  kp_torso: 527.5300909710207
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0746286199290325
    - 0.6899136553593365
    - -1.1200135581280413
    - 0.05970557056955721
    - -0.08216471367106801
    - 0.4213805490491472
    - 0.4901409046171737
  - - 0.027232053252353897
    - -1.3911149968648038
    - -0.720067019952658
    - -0.13737590639185943
    - -0.03125973200917586
    - -0.27975526734002437
    - 0.7945138693189471
  - - 0.0746286199290325
    - -0.08216471367106801
    - 0.4213805490491472
    - 0.4901409046171737
    - 0.6899136553593365
    - -1.1200135581280413
    - 0.05970557056955721
  - - 0.027232053252353897
    - -0.03125973200917586
    - -0.27975526734002437
    - 0.7945138693189471
    - -1.3911149968648038
    - -0.720067019952658
    - -0.13737590639185943
