walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1610815496637636
  g: -9.8
  kd:
  - 33.474111314969655
  - 42.474111314969655
  - 33.474111314969655
  - 33.474111314969655
  - 42.474111314969655
  - 33.474111314969655
  kd_torso: 261.28637620577814
  kp:
  - 334.7411131496965
  - 424.7411131496965
  - 334.7411131496965
  - 334.7411131496965
  - 424.7411131496965
  - 334.7411131496965
  kp_torso: 531.4395775796935
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.055696649771469584
    - 0.6734049596481785
    - -1.1572137413603971
    - 0.1585010862496419
    - -0.007306297265813186
    - 0.33645143162059954
    - 0.4688238043515047
  - - 0.011333668175284806
    - -1.3889870917188316
    - -0.7527100052969529
    - -0.2524027396057864
    - 0.026777761176558702
    - -0.3335042620365328
    - 0.5458091074876454
  - - 0.055696649771469584
    - -0.007306297265813186
    - 0.33645143162059954
    - 0.4688238043515047
    - 0.6734049596481785
    - -1.1572137413603971
    - 0.1585010862496419
  - - 0.011333668175284806
    - 0.026777761176558702
    - -0.3335042620365328
    - 0.5458091074876454
    - -1.3889870917188316
    - -0.7527100052969529
    - -0.2524027396057864
