walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2929559808026281
  g: -9.8
  kd:
  - 30.882126675518045
  - 39.882126675518045
  - 30.882126675518045
  - 30.882126675518045
  - 39.882126675518045
  - 30.882126675518045
  kd_torso: 219.74395673591718
  kp:
  - 308.82126675518043
  - 398.82126675518043
  - 308.82126675518043
  - 308.82126675518043
  - 398.82126675518043
  - 308.82126675518043
  kp_torso: 471.4520792681337
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.0025821389843660933
    - 0.45946489073647084
    - -0.6805084865857869
    - 0.5313547566465913
    - 0.006375984628753738
    - 0.4236513896398023
    - -0.17704107714649336
  - - -0.23665581658857052
    - -0.8795004607734733
    - -0.02656252557024065
    - 0.4505616978817198
    - -0.025599793887497627
    - 0.14626950394137866
    - 0.4132544460799169
  - - -0.0025821389843660933
    - 0.006375984628753738
    - 0.4236513896398023
    - -0.17704107714649336
    - 0.45946489073647084
    - -0.6805084865857869
    - 0.5313547566465913
  - - -0.23665581658857052
    - -0.025599793887497627
    - 0.14626950394137866
    - 0.4132544460799169
    - -0.8795004607734733
    - -0.02656252557024065
    - 0.4505616978817198
