walk:
  c_d: 1.6
  c_v: 0
  dt: 0.17147191249021404
  g: -9.8
  kd:
  - 31.963550005514367
  - 40.96355000551437
  - 31.963550005514367
  - 31.963550005514367
  - 40.96355000551437
  - 31.963550005514367
  kd_torso: 269.0654126559411
  kp:
  - 319.63550005514367
  - 409.63550005514367
  - 319.63550005514367
  - 319.63550005514367
  - 409.63550005514367
  - 319.63550005514367
  kp_torso: 501.61195112763926
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.06303759763598515
    - 0.7064910922758464
    - -1.3063847117545604
    - 0.20293921141802126
    - 0.05332285862927244
    - 0.2756943171058417
    - 0.4390889558435808
  - - -0.056968151805836156
    - -1.4759504397647096
    - -0.3839924068677685
    - -0.22181390381184862
    - 0.0018778757951532117
    - -0.32297555623566443
    - -0.006702860880641967
  - - 0.06303759763598515
    - 0.05332285862927244
    - 0.2756943171058417
    - 0.4390889558435808
    - 0.7064910922758464
    - -1.3063847117545604
    - 0.20293921141802126
  - - -0.056968151805836156
    - 0.0018778757951532117
    - -0.32297555623566443
    - -0.006702860880641967
    - -1.4759504397647096
    - -0.3839924068677685
    - -0.22181390381184862
