walk:
  c_d: 1.6
  c_v: 0
  dt: 0.21108154966376358
  g: -9.8
  kd:
  - 32.13512936870139
  - 41.13512936870139
  - 32.13512936870139
  - 32.13512936870139
  - 41.13512936870139
  - 32.13512936870139
  kd_torso: 258.6086000881223
  kp:
  - 321.3512936870139
  - 411.3512936870139
  - 321.3512936870139
  - 321.3512936870139
  - 411.3512936870139
  - 321.3512936870139
  kp_torso: 532.1702073062748
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.05122559532360108
    - 0.7233910206602108
    - -1.1577483822212864
    - 0.1660373278538581
    - 0.011168717302789621
    - 0.3901932473983243
    - 0.45592928813775185
  - - 0.09103312731915303
    - -1.4076075627066909
    - -0.6890566859235778
    - -0.17887631592041525
    - -0.035466307582860505
    - -0.33219350270071457
    - 0.5509019019949866
  - - 0.05122559532360108
    - 0.011168717302789621
    - 0.3901932473983243
    - 0.45592928813775185
    - 0.7233910206602108
    - -1.1577483822212864
    - 0.1660373278538581
  - - 0.09103312731915303
    - -0.035466307582860505
    - -0.33219350270071457
    - 0.5509019019949866
    - -1.4076075627066909
    - -0.6890566859235778
    - -0.17887631592041525
