walk:
  c_d: 1.6
  c_v: 0
  dt: 0.19425037837849027
  g: -9.8
  kd:
  - 30.977319434340586
  - 39.977319434340586
  - 30.977319434340586
  - 30.977319434340586
  - 39.977319434340586
  - 30.977319434340586
  kd_torso: 232.54964414905083
  kp:
  - 309.77319434340586
  - 399.77319434340586
  - 309.77319434340586
  - 309.77319434340586
  - 399.77319434340586
  - 309.77319434340586
  kp_torso: 473.46206828257294
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0445573860585502
    - 0.476013031928532
    - -0.6401767644443833
    - 0.5838459031807733
    - -0.056589584472456995
    - 0.351351471631763
    - 0.017051168218907772
  - - -0.2232351612772444
    - -0.521550384185409
    - -0.3413700745735689
    - 0.3684376424193081
    - -0.010266349218531737
    - 0.04454233062187943
    - 0.5273892166022667
  - - 0.0445573860585502
    - -0.056589584472456995
    - 0.351351471631763
    - 0.017051168218907772
    - 0.476013031928532
    - -0.6401767644443833
    - 0.5838459031807733
  - - -0.2232351612772444
    - -0.010266349218531737
    - 0.04454233062187943
    - 0.5273892166022667
    - -0.521550384185409
    - -0.3413700745735689
    - 0.3684376424193081
