walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1438837584745536
  g: -9.8
  kd:
  - 33.40746587633243
  - 42.40746587633243
  - 33.40746587633243
  - 33.40746587633243
  - 42.40746587633243
  - 33.40746587633243
  kd_torso: 267.9467174657769
  kp:
  - 334.0746587633243
  - 424.0746587633243
  - 334.0746587633243
  - 334.0746587633243
  - 424.0746587633243
  - 334.0746587633243
  kp_torso: 524.4745852563286
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0026029295671124233
    - 0.7558587281637217
    - -1.131513789890969
    - 0.2335592696649591
    - 0.06134006931474753
    - 0.32534439322218434
    - 0.4046106173872721
  - - 0.04283587948901166
    - -1.419239704863684
    - -0.6050716535879024
    - -0.2875070643744756
    - 0.04135582751327192
    - -0.40556481006361506
    - 0.31471687927560354
  - - 0.0026029295671124233
    - 0.06134006931474753
    - 0.32534439322218434
    - 0.4046106173872721
    - 0.7558587281637217
    - -1.131513789890969
    - 0.2335592696649591
  - - 0.04283587948901166
    - 0.04135582751327192
    - -0.40556481006361506
    - 0.31471687927560354
    - -1.419239704863684
    - -0.6050716535879024
    - -0.2875070643744756
