walk:
  c_d: 1.6
  c_v: 0
  dt: 0.29622605471210295
  g: -9.8
  kd:
  - 31.749517135897793
  - 40.7495171358978
  - 31.749517135897793
  - 31.749517135897793
  - 40.7495171358978
  - 31.749517135897793
  kd_torso: 220.5960660209564
  kp:
  - 317.4951713589779
  - 407.4951713589779
  - 317.4951713589779
  - 317.4951713589779
  - 407.4951713589779
  - 317.4951713589779
  kp_torso: 488.35480597543545
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.012707767120294755
    - 0.4382599113660167
    - -0.7235267864675891
    - 0.5164998981087664
    - 0.04388315884240453
    - 0.5
    - -0.16633419999270058
  - - -0.2978443084548674
    - -0.7976335459511689
    - -0.04431944543510368
    - 0.5300417939042125
    - -0.005646104744697674
    - 0.048306811922525686
    - 0.47073182200808583
  - - 0.012707767120294755
    - 0.04388315884240453
    - 0.5
    - -0.16633419999270058
    - 0.4382599113660167
    - -0.7235267864675891
    - 0.5164998981087664
  - - -0.2978443084548674
    - -0.005646104744697674
    - 0.048306811922525686
    - 0.47073182200808583
    - -0.7976335459511689
    - -0.04431944543510368
    - 0.5300417939042125
