walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1954472437589207
  g: -9.8
  kd:
  - 32.86418731090419
  - 41.86418731090419
  - 32.86418731090419
  - 32.86418731090419
  - 41.86418731090419
  - 32.86418731090419
  kd_torso: 267.67255998638143
  kp:
  - 328.6418731090419
  - 418.6418731090419
  - 328.6418731090419
  - 328.6418731090419
  - 418.6418731090419
  - 328.6418731090419
  kp_torso: 520.4990012375622
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.067969047892237
    - 0.6660736348907583
    - -1.086825701783209
    - 0.16378921838799404
    - -0.06576036500460819
    - 0.32109973498900324
    - 0.5655757583260815
  - - 0.020875897216490885
    - -1.4095734796381982
    - -0.7140323892246373
    - -0.06685817630835646
    - -0.05951234630656094
    - -0.14053653898096613
    - 0.8920362064567678
  - - 0.067969047892237
    - -0.06576036500460819
    - 0.32109973498900324
    - 0.5655757583260815
    - 0.6660736348907583
    - -1.086825701783209
    - 0.16378921838799404
  - - 0.020875897216490885
    - -0.05951234630656094
    - -0.14053653898096613
    - 0.8920362064567678
    - -1.4095734796381982
    - -0.7140323892246373
    - -0.06685817630835646
