walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2108167191728338
  g: -9.8
  kd:
  - 31.68183578169665
  - 40.68183578169665
  - 31.68183578169665
  - 31.68183578169665
  - 40.68183578169665
  - 31.68183578169665
  kd_torso: 234.7089687823027
  kp:
  - 316.81835781696645
  - 406.81835781696645
  - 316.81835781696645
  - 316.81835781696645
  - 406.81835781696645
  - 316.81835781696645
  kp_torso: 478.9293714299552
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03976210255924127
    - 0.46239138641134647
    - -0.6764469280747631
    - 0.5633632295364291
    - -0.0019165529986343334
    - 0.2967698460013307
    - 0.019300559546110506
  - - -0.21029165321711565
    - -0.5558145036183282
    - -0.339042770577705
    - 0.3874720498424084
    - 0.011326897113986708
    - -0.002562350114058476
    - 0.4942455394836731
  - - 0.03976210255924127
    - -0.0019165529986343334
    - 0.2967698460013307
    - 0.019300559546110506
    - 0.46239138641134647
    - -0.6764469280747631
    - 0.5633632295364291
  - - -0.21029165321711565
    - 0.011326897113986708
    - -0.002562350114058476
    - 0.4942455394836731
    - -0.5558145036183282
    - -0.339042770577705
    - 0.3874720498424084
