walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2954129865203865
  g: -9.8
  kd:
  - 30.83994989464446
  - 39.83994989464446
  - 30.83994989464446
  - 30.83994989464446
  - 39.83994989464446
  - 30.83994989464446
  kd_torso: 221.6330250867757
  kp:
  - 308.39949894644457
  - 398.39949894644457
  - 308.39949894644457
  - 308.39949894644457
  - 398.39949894644457
  - 308.39949894644457
  kp_torso: 481.74772587720076
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.021411257166667558
    - 0.4091321771542441
    - -0.7146432637136513
    - 0.502275708749451
    - 0.007225273997460606
    - 0.4949636164656289
    - -0.11931639347548378
  - - -0.2167171612950904
    - -0.805890542687432
    - -0.03551640324118005
    - 0.5310221048250116
    - -0.004699752736656587
    - 0.11210807186593547
    - 0.29798991801301467
  - - 0.021411257166667558
    - 0.007225273997460606
    - 0.4949636164656289
    - -0.11931639347548378
    - 0.4091321771542441
    - -0.7146432637136513
    - 0.502275708749451
  - - -0.2167171612950904
    - -0.004699752736656587
    - 0.11210807186593547
    - 0.29798991801301467
    - -0.805890542687432
    - -0.03551640324118005
    - 0.5310221048250116
