walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24622605471210296
  g: -9.8
  kd:
  - 31.581036988457296
  - 40.5810369884573
  - 31.581036988457296
  - 31.581036988457296
  - 40.5810369884573
  - 31.581036988457296
  kd_torso: 225.0133566546022
  kp:
  - 315.81036988457294
  - 405.81036988457294
  - 315.81036988457294
  - 315.81036988457294
  - 405.81036988457294
  - 315.81036988457294
  kp_torso: 478.2466126592298
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0026093369532370903
    - 0.5680377678740833
    - -0.7867746360874246
    - 0.5502976291224925
    - 0.022664255969137435
    - 0.5
    - -0.12613585857314824
  - - -0.3
    - -0.6451722585492256
    - -0.005359976980777795
    - 0.512197187036967
    - 0.02506540489650882
    - 0.09602725497394836
    - 0.4938076117265791
  - - 0.0026093369532370903
    - 0.022664255969137435
    - 0.5
    - -0.12613585857314824
    - 0.5680377678740833
    - -0.7867746360874246
    - 0.5502976291224925
  - - -0.3
    - 0.02506540489650882
    - 0.09602725497394836
    - 0.4938076117265791
    - -0.6451722585492256
    - -0.005359976980777795
    - 0.512197187036967
