running_0.10:
  c_d: 0.01
  c_v: 0.2
  dt: 0.2055703056704164
  g: -9.8
  kd:
  - 49.24262365069126
  - 49.24262365069126
  - 49.24262365069126
  - 49.24262365069126
  - 49.24262365069126
  - 49.24262365069126
  kd_torso: 166.66251091159282
  kp:
  - 492.4262365069125
  - 492.4262365069125
  - 492.4262365069125
  - 492.4262365069125
  - 492.4262365069125
  - 492.4262365069125
  kp_torso: 462.59082217547115
  max_torque: 1000
  mu: 0.65
  targets:
  - - 0.0292116850560989
    - 1.134284505340774
    - -1.722760804018626
    - 0.19578887039388443
    - 0.1259082217547115
    - -0.12424751801417587
    - -0.12054153914316028
  - - -0.12233160894964147
    - -1.7038520188452995
    - -0.17548532816283757
    - -0.11893537520856587
    - 0.06662510911592812
    - -0.37690197453700475
    - 0.37363687869463474
  - - 0.0292116850560989
    - 0.1259082217547115
    - -0.12424751801417587
    - -0.12054153914316028
    - 1.134284505340774
    - -1.722760804018626
    - 0.19578887039388443
  - - -0.12233160894964147
    - 0.06662510911592812
    - -0.37690197453700475
    - 0.37363687869463474
    - -1.7038520188452995
    - -0.17548532816283757
    - -0.11893537520856587
