walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1792715190754285
  g: -9.8
  kd:
  - 31.43391002793041
  - 40.43391002793041
  - 31.43391002793041
  - 31.43391002793041
  - 40.43391002793041
  - 31.43391002793041
  kd_torso: 268.8776250764258
  kp:
  - 314.3391002793041
  - 404.3391002793041
  - 314.3391002793041
  - 314.3391002793041
  - 404.3391002793041
  - 314.3391002793041
  kp_torso: 496.27966526471204
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.02698606952742621
    - 0.7288596104545129
    - -1.266729071583953
    - 0.22660910471946755
    - 0.09143079638108646
    - 0.26884817149287754
    - 0.4915676747188178
  - - 0.04979294473904325
    - -1.4286211126318993
    - -0.2874345228723976
    - -0.17232334468499882
    - 0.02148982554758453
    - -0.3755679252049666
    - -0.08185711826881915
  - - 0.02698606952742621
    - 0.09143079638108646
    - 0.26884817149287754
    - 0.4915676747188178
    - 0.7288596104545129
    - -1.266729071583953
    - 0.22660910471946755
  - - 0.04979294473904325
    - 0.02148982554758453
    - -0.3755679252049666
    - -0.08185711826881915
    - -1.4286211126318993
    - -0.2874345228723976
    - -0.17232334468499882
