walk:
  c_d: 1.6
  c_v: 0
  dt: 0.23196395593435712
  g: -9.8
  kd:
  - 30.509014110342658
  - 39.50901411034266
  - 30.509014110342658
  - 30.509014110342658
  - 39.50901411034266
  - 30.509014110342658
  kd_torso: 219.65990575936445
  kp:
  - 305.09014110342656
  - 395.09014110342656
  - 305.09014110342656
  - 305.09014110342656
  - 395.09014110342656
  - 305.09014110342656
  kp_torso: 459.4808314502253
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.01334388716623091
    - 0.48033909017615883
    - -0.5196908709007779
    - 0.5232397192518577
    - -0.09236766341166845
    - 0.4196554525591662
    - 0.1053560749508503
  - - -0.3
    - -0.5403045791863159
    - -0.3821952522516914
    - 0.3439147807185231
    - -0.010243017877873968
    - -0.10856201051686087
    - 0.4248536964942878
  - - 0.01334388716623091
    - -0.09236766341166845
    - 0.4196554525591662
    - 0.1053560749508503
    - 0.48033909017615883
    - -0.5196908709007779
    - 0.5232397192518577
  - - -0.3
    - -0.010243017877873968
    - -0.10856201051686087
    - 0.4248536964942878
    - -0.5403045791863159
    - -0.3821952522516914
    - 0.3439147807185231
