walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24937941048948944
  g: -9.8
  kd:
  - 29.372119030226543
  - 38.37211903022654
  - 29.372119030226543
  - 29.372119030226543
  - 38.37211903022654
  - 29.372119030226543
  kd_torso: 219.99901018791883
  kp:
  - 293.7211903022654
  - 383.7211903022654
  - 293.7211903022654
  - 293.7211903022654
  - 383.7211903022654
  - 293.7211903022654
  kp_torso: 482.083670993811
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.04750952060448352
    - 0.7121014147510496
    - -1.0632942755009678
    - 0.44248300682559183
    - 0.01346081632237221
    - 0.2029422467207085
    - -0.006671429473658723
  - - -0.11667607883297976
    - -1.3500167211372431
    - -0.04616723713534419
    - 0.4693875723473183
    - -0.08395166903163448
    - -0.001350194709470922
    - 0.17141619932970578
  - - 0.04750952060448352
    - 0.01346081632237221
    - 0.2029422467207085
    - -0.006671429473658723
    - 0.7121014147510496
    - -1.0632942755009678
    - 0.44248300682559183
  - - -0.11667607883297976
    - -0.08395166903163448
    - -0.001350194709470922
    - 0.17141619932970578
    - -1.3500167211372431
    - -0.04616723713534419
    - 0.4693875723473183
