walk:
  c_d: 1.6
  c_v: 0
  dt: 0.21578986751727766
  g: -9.8
  kd:
  - 30.47086484404599
  - 39.47086484404599
  - 30.47086484404599
  - 30.47086484404599
  - 39.47086484404599
  - 30.47086484404599
  kd_torso: 212.64609878475133
  kp:
  - 304.7086484404599
  - 394.7086484404599
  - 304.7086484404599
  - 304.7086484404599
  - 394.7086484404599
  - 304.7086484404599
  kp_torso: 454.2451659642507
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.019879004090636053
    - 0.3824507634692872
    - -0.44796421948182963
    - 0.527638998344113
    - -0.05235665485974585
    - 0.3973275026827082
    - 0.08476034914232092
  - - -0.3
    - -0.5863383287314454
    - -0.3997658837091661
    - 0.2704484778088352
    - -0.07013806974613115
    - -0.09344085235649818
    - 0.432073054848542
  - - 0.019879004090636053
    - -0.05235665485974585
    - 0.3973275026827082
    - 0.08476034914232092
    - 0.3824507634692872
    - -0.44796421948182963
    - 0.527638998344113
  - - -0.3
    - -0.07013806974613115
    - -0.09344085235649818
    - 0.432073054848542
    - -0.5863383287314454
    - -0.3997658837091661
    - 0.2704484778088352
