walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1671872158197888
  g: -9.8
  kd:
  - 30.897609199506412
  - 39.89760919950641
  - 30.897609199506412
  - 30.897609199506412
  - 39.89760919950641
  - 30.897609199506412
  kd_torso: 266.7286425216673
  kp:
  - 308.9760919950641
  - 398.9760919950641
  - 308.9760919950641
  - 308.9760919950641
  - 398.9760919950641
  - 308.9760919950641
  kp_torso: 487.1365856266034
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.0038822039280393336
    - 0.8006977384668127
    - -1.2315667689758456
    - 0.27331680412634646
    - 0.021098818246943863
    - 0.22459726264404545
    - 0.4619155605512731
  - - 0.044959620054614145
    - -1.3603093587269657
    - -0.2575509568698071
    - -0.1694406555763943
    - -0.026478205054898105
    - -0.35464395399602094
    - -0.1258972656167253
  - - 0.0038822039280393336
    - 0.021098818246943863
    - 0.22459726264404545
    - 0.4619155605512731
    - 0.8006977384668127
    - -1.2315667689758456
    - 0.27331680412634646
  - - 0.044959620054614145
    - -0.026478205054898105
    - -0.35464395399602094
    - -0.1258972656167253
    - -1.3603093587269657
    - -0.2575509568698071
    - -0.1694406555763943
