walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2636718101106062
  g: -9.8
  kd:
  - 30.199625825762993
  - 39.19962582576299
  - 30.199625825762993
  - 30.199625825762993
  - 39.19962582576299
  - 30.199625825762993
  kd_torso: 208.82189631135384
  kp:
  - 301.9962582576299
  - 391.9962582576299
  - 301.9962582576299
  - 301.9962582576299
  - 391.9962582576299
  - 301.9962582576299
  kp_torso: 471.3073329712963
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.07439556445578613
    - 0.5103219475815728
    - -0.998341546553041
    - 0.3788951391928655
    - -0.012281209474863431
    - 0.22780929715183246
    - 0.04264389270855151
  - - -0.3
    - -1.0025589339824998
    - -0.007790522335240142
    - 0.5300942982922549
    - 0.03024571986232832
    - -0.023537665700981474
    - 0.15410502899787476
  - - 0.07439556445578613
    - -0.012281209474863431
    - 0.22780929715183246
    - 0.04264389270855151
    - 0.5103219475815728
    - -0.998341546553041
    - 0.3788951391928655
  - - -0.3
    - 0.03024571986232832
    - -0.023537665700981474
    - 0.15410502899787476
    - -1.0025589339824998
    - -0.007790522335240142
    - 0.5300942982922549
