walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2672066015620974
  g: -9.8
  kd:
  - 30.137770940640078
  - 39.13777094064008
  - 30.137770940640078
  - 30.137770940640078
  - 39.13777094064008
  - 30.137770940640078
  kd_torso: 211.79558780224562
  kp:
  - 301.37770940640075
  - 391.37770940640075
  - 301.37770940640075
  - 301.37770940640075
  - 391.37770940640075
  - 301.37770940640075
  kp_torso: 478.31637805161137
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.06659783170095476
    - 0.5151899377541901
    - -1.0122859857150377
    - 0.4077845340653661
    - 0.06213018075035458
    - 0.32738000501077497
    - -0.030298381616110044
  - - -0.29977913059181766
    - -0.9129417126019563
    - -0.0029471874952880575
    - 0.4469250297564534
    - 0.008357643183410595
    - 0.0033992320002639576
    - 0.1890487037495377
  - - 0.06659783170095476
    - 0.06213018075035458
    - 0.32738000501077497
    - -0.030298381616110044
    - 0.5151899377541901
    - -1.0122859857150377
    - 0.4077845340653661
  - - -0.29977913059181766
    - 0.008357643183410595
    - 0.0033992320002639576
    - 0.1890487037495377
    - -0.9129417126019563
    - -0.0029471874952880575
    - 0.4469250297564534
