walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2357576295066896
  g: -9.8
  kd:
  - 30.82845370316413
  - 39.82845370316413
  - 30.82845370316413
  - 30.82845370316413
  - 39.82845370316413
  - 30.82845370316413
  kd_torso: 234.69568916082918
  kp:
  - 308.28453703164126
  - 398.28453703164126
  - 308.28453703164126
  - 308.28453703164126
  - 398.28453703164126
  - 308.28453703164126
  kp_torso: 480.14427171847467
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03595146931881842
    - 0.48765197215799816
    - -0.7147761239407205
    - 0.4848481707470468
    - 0.03976111485954204
    - 0.4453725989643008
    - 0.045441058433453176
  - - -0.19353775590780165
    - -0.6419921563099716
    - -0.2927220131547805
    - 0.4534484003828398
    - 0.04547111939326204
    - 0.11637473036070732
    - 0.5638741261652895
  - - 0.03595146931881842
    - 0.03976111485954204
    - 0.4453725989643008
    - 0.045441058433453176
    - 0.48765197215799816
    - -0.7147761239407205
    - 0.4848481707470468
  - - -0.19353775590780165
    - 0.04547111939326204
    - 0.11637473036070732
    - 0.5638741261652895
    - -0.6419921563099716
    - -0.2927220131547805
    - 0.4534484003828398
