walk:
  c_d: 1.6
  c_v: 0
  dt: 0.20433306503728105
  g: -9.8
  kd:
  - 33.79921296722274
  - 42.79921296722274
  - 33.79921296722274
  - 33.79921296722274
  - 42.79921296722274
  - 33.79921296722274
  kd_torso: 267.5581484433127
  kp:
  - 337.9921296722274
  - 427.9921296722274
  - 337.9921296722274
  - 337.9921296722274
  - 427.9921296722274
  - 337.9921296722274
  kp_torso: 535.7465623381275
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.06618483747591786
    - 0.6150232574983506
    - -1.1376062556467745
    - 0.07333802773702854
    - 0.03811362270262127
    - 0.3341523895374559
    - 0.44348720697964206
  - - 0.03492468084846925
    - -1.4185779471064175
    - -0.6508013642393695
    - -0.19424833378791723
    - 0.07205876028542445
    - -0.28494456652084577
    - 0.7445325869414329
  - - 0.06618483747591786
    - 0.03811362270262127
    - 0.3341523895374559
    - 0.44348720697964206
    - 0.6150232574983506
    - -1.1376062556467745
    - 0.07333802773702854
  - - 0.03492468084846925
    - 0.07205876028542445
    - -0.28494456652084577
    - 0.7445325869414329
    - -1.4185779471064175
    - -0.6508013642393695
    - -0.19424833378791723
