walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24425037837849028
  g: -9.8
  kd:
  - 30.467692027156183
  - 39.46769202715618
  - 30.467692027156183
  - 30.467692027156183
  - 39.46769202715618
  - 30.467692027156183
  kd_torso: 220.68420754715186
  kp:
  - 304.6769202715618
  - 394.6769202715618
  - 304.6769202715618
  - 304.6769202715618
  - 394.6769202715618
  - 304.6769202715618
  kp_torso: 468.71759779139217
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.01878247612396044
    - 0.5163624041689111
    - -0.5978565137236447
    - 0.6037393985200917
    - -0.04744470491180763
    - 0.4179230102455105
    - 0.07872651003115172
  - - -0.26941743832601206
    - -0.47754124305917617
    - -0.3487736074207843
    - 0.3136221981531327
    - -0.11865436601898982
    - -0.08129866764274274
    - 0.4956357541720387
  - - 0.01878247612396044
    - -0.04744470491180763
    - 0.4179230102455105
    - 0.07872651003115172
    - 0.5163624041689111
    - -0.5978565137236447
    - 0.6037393985200917
  - - -0.26941743832601206
    - -0.11865436601898982
    - -0.08129866764274274
    - 0.4956357541720387
    - -0.47754124305917617
    - -0.3487736074207843
    - 0.3136221981531327
