walk:
  c_d: 1.6
  c_v: 0
  dt: 0.18102938835118845
  g: -9.8
  kd:
  - 31.801647690927087
  - 40.80164769092709
  - 31.801647690927087
  - 31.801647690927087
  - 40.80164769092709
  - 31.801647690927087
  kd_torso: 252.8071062321271
  kp:
  - 318.01647690927086
  - 408.01647690927086
  - 318.01647690927086
  - 318.01647690927086
  - 408.01647690927086
  - 318.01647690927086
  kp_torso: 489.23815860704104
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.007623122307082149
    - 0.8749432868735617
    - -1.0471560373198365
    - 0.27671549716932636
    - -0.05094564184346784
    - 0.19831286161981937
    - 0.28634382438641875
  - - 0.031382807285632405
    - -1.4194260440597986
    - -0.3369214044377304
    - -0.01011222284780492
    - -0.04865382425442161
    - -0.21685310467023747
    - 0.04044435898769619
  - - -0.007623122307082149
    - -0.05094564184346784
    - 0.19831286161981937
    - 0.28634382438641875
    - 0.8749432868735617
    - -1.0471560373198365
    - 0.27671549716932636
  - - 0.031382807285632405
    - -0.04865382425442161
    - -0.21685310467023747
    - 0.04044435898769619
    - -1.4194260440597986
    - -0.3369214044377304
    - -0.01011222284780492
