walk:
  c_d: 1.6
  c_v: 0
  dt: 0.20601493857811207
  g: -9.8
  kd:
  - 32.751577052979165
  - 41.751577052979165
  - 32.751577052979165
  - 32.751577052979165
  - 41.751577052979165
  - 32.751577052979165
  kd_torso: 258.69948898172026
  kp:
  - 327.5157705297916
  - 417.5157705297916
  - 327.5157705297916
  - 327.5157705297916
  - 417.5157705297916
  - 327.5157705297916
  kp_torso: 510.11391637026884
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.07178598159145809
    - 0.6611057274108355
    - -1.1660042514330917
    - 0.23800502658627684
    - -0.10651994295008306
    - 0.2893262385766684
    - 0.3733148314349051
  - - -0.051086513088029355
    - -1.3908781134458255
    - -0.48768967969969185
    - -0.21592399181371616
    - -0.020842913530289078
    - -0.21876185994574504
    - 0.3100625002690022
  - - 0.07178598159145809
    - -0.10651994295008306
    - 0.2893262385766684
    - 0.3733148314349051
    - 0.6611057274108355
    - -1.1660042514330917
    - 0.23800502658627684
  - - -0.051086513088029355
    - -0.020842913530289078
    - -0.21876185994574504
    - 0.3100625002690022
    - -1.3908781134458255
    - -0.48768967969969185
    - -0.21592399181371616
