walk:
  c_d: 1.6
  c_v: 0
  dt: 0.28431435637324814
  g: -9.8
  kd:
  - 28.228420167554056
  - 37.228420167554056
  - 28.228420167554056
  - 28.228420167554056
  - 37.228420167554056
  - 28.228420167554056
  kd_torso: 237.26054309769853
  kp:
  - 282.28420167554054
  - 372.28420167554054
  - 282.28420167554054
  - 282.28420167554054
  - 372.28420167554054
  - 282.28420167554054
  kp_torso: 477.23179648755763
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03397540272069896
    - 0.8648855219170365
    - -1.0640488265258439
    - 0.22535450198840848
    - -0.022995205327307963
    - 0.20244796030861825
    - 0.123984445724377
  - - -0.039052640872999554
    - -1.2959239445086042
    - -0.12080981356752392
    - 0.27676660265202435
    - 0.027323655416677778
    - 0.01957813016208143
    - 0.41131814856239907
  - - 0.03397540272069896
    - -0.022995205327307963
    - 0.20244796030861825
    - 0.123984445724377
    - 0.8648855219170365
    - -1.0640488265258439
    - 0.22535450198840848
  - - -0.039052640872999554
    - 0.027323655416677778
    - 0.01957813016208143
    - 0.41131814856239907
    - -1.2959239445086042
    - -0.12080981356752392
    - 0.27676660265202435
