walk:
  c_d: 1.6
  c_v: 0
  dt: 0.27386928887841444
  g: -9.8
  kd:
  - 29.958411119898173
  - 38.95841111989817
  - 29.958411119898173
  - 29.958411119898173
  - 38.95841111989817
  - 29.958411119898173
  kd_torso: 208.49133926539443
  kp:
  - 299.5841111989817
  - 389.5841111989817
  - 299.5841111989817
  - 299.5841111989817
  - 389.5841111989817
  - 299.5841111989817
  kp_torso: 475.623137851609
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.04468639353745811
    - 0.6131045900299381
    - -1.0198014823742352
    - 0.4418671604999795
    - -0.06460533142201996
    - 0.14851499262926493
    - -0.03652550877723847
  - - -0.0727125999119129
    - -1.2607354483061068
    - 0.005556682928476914
    - 0.40868992710732654
    - -0.11507670922524392
    - -0.03304192686942544
    - 0.16508610606304494
  - - 0.04468639353745811
    - -0.06460533142201996
    - 0.14851499262926493
    - -0.03652550877723847
    - 0.6131045900299381
    - -1.0198014823742352
    - 0.4418671604999795
  - - -0.0727125999119129
    - -0.11507670922524392
    - -0.03304192686942544
    - 0.16508610606304494
    - -1.2607354483061068
    - 0.005556682928476914
    - 0.40868992710732654
