walk:
  c_d: 1.6
  c_v: 0
  dt: 0.29622605471210295
  g: -9.8
  kd:
  - 31.06748629064577
  - 40.067486290645775
  - 31.06748629064577
  - 31.06748629064577
  - 40.067486290645775
  - 31.06748629064577
  kd_torso: 222.50681616495132
  kp:
  - 310.6748629064577
  - 400.6748629064577
  - 310.6748629064577
  - 310.6748629064577
  - 400.6748629064577
  - 310.6748629064577
  kp_torso: 475.9801870623161
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.006851167033025638
    - 0.5184795250393499
    - -0.7254174287176247
    - 0.4556287555708759
    - -0.004666410147914742
    - 0.47276831612604675
    - -0.1990434240827646
  - - -0.3
    - -0.6522125629166151
    - -0.026606041719009432
    - 0.5688378735744724
    - -0.012046597088110159
    - 0.02817120495335361
    - 0.4248875950131211
  - - -0.006851167033025638
    - -0.004666410147914742
    - 0.47276831612604675
    - -0.1990434240827646
    - 0.5184795250393499
    - -0.7254174287176247
    - 0.4556287555708759
  - - -0.3
    - -0.012046597088110159
    - 0.02817120495335361
    - 0.4248875950131211
    - -0.6522125629166151
    - -0.026606041719009432
    - 0.5688378735744724
