walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24394876563272033
  g: -9.8
  kd:
  - 31.58953644446825
  - 40.58953644446825
  - 31.58953644446825
  - 31.58953644446825
  - 40.58953644446825
  - 31.58953644446825
  kd_torso: 230.11609898881645
  kp:
  - 315.8953644446825
  - 405.8953644446825
  - 315.8953644446825
  - 315.8953644446825
  - 405.8953644446825
  - 315.8953644446825
  kp_torso: 483.06872995178645
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03260234098133635
    - 0.5101679119811221
    - -0.845265325316612
    - 0.5747288112241334
    - 0.04822117292556648
    - 0.5
    - -0.09477885141931824
  - - -0.28590253526987297
    - -0.705354302375103
    - -0.07237899780760282
    - 0.5592628773880464
    - 0.05102742334214247
    - 0.0628189293596271
    - 0.47121137473944186
  - - 0.03260234098133635
    - 0.04822117292556648
    - 0.5
    - -0.09477885141931824
    - 0.5101679119811221
    - -0.845265325316612
    - 0.5747288112241334
  - - -0.28590253526987297
    - 0.05102742334214247
    - 0.0628189293596271
    - 0.47121137473944186
    - -0.705354302375103
    - -0.07237899780760282
    - 0.5592628773880464
