walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1816137198701263
  g: -9.8
  kd:
  - 31.44375201392671
  - 40.44375201392671
  - 31.44375201392671
  - 31.44375201392671
  - 40.44375201392671
  - 31.44375201392671
  kd_torso: 250.09959738779705
  kp:
  - 314.43752013926706
  - 404.43752013926706
  - 314.43752013926706
  - 314.43752013926706
  - 404.43752013926706
  - 314.43752013926706
  kp_torso: 489.80531459126087
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.011653247098250306
    - 0.9426188015395123
    - -1.1761694069205297
    - 0.16651209459883373
    - 0.01349542814859526
    - 0.20207612311520531
    - 0.2911735942341875
  - - 0.0928002217699257
    - -1.38689488883578
    - -0.3056271145528548
    - -0.011616221450625502
    - -0.00303995608560189
    - -0.23768429268623428
    - -0.00651436445478213
  - - -0.011653247098250306
    - 0.01349542814859526
    - 0.20207612311520531
    - 0.2911735942341875
    - 0.9426188015395123
    - -1.1761694069205297
    - 0.16651209459883373
  - - 0.0928002217699257
    - -0.00303995608560189
    - -0.23768429268623428
    - -0.00651436445478213
    - -1.38689488883578
    - -0.3056271145528548
    - -0.011616221450625502
