walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2947710481508564
  g: -9.8
  kd:
  - 29.969360376728776
  - 38.96936037672878
  - 29.969360376728776
  - 29.969360376728776
  - 38.96936037672878
  - 29.969360376728776
  kd_torso: 205.33524198037162
  kp:
  - 299.69360376728775
  - 389.69360376728775
  - 299.69360376728775
  - 299.69360376728775
  - 389.69360376728775
  - 299.69360376728775
  kp_torso: 479.24846092154166
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.06538039323429988
    - 0.5993431840347035
    - -1.0534877061781343
    - 0.48437482297568635
    - 0.03625323069932703
    - 0.20914625568421
    - 0.045451224883259096
  - - -0.14571508175036665
    - -1.172516028256826
    - 0.09935198975744082
    - 0.404822053148406
    - -0.031560972850228165
    - -0.09560005311949232
    - 0.1312618790102857
  - - 0.06538039323429988
    - 0.03625323069932703
    - 0.20914625568421
    - 0.045451224883259096
    - 0.5993431840347035
    - -1.0534877061781343
    - 0.48437482297568635
  - - -0.14571508175036665
    - -0.031560972850228165
    - -0.09560005311949232
    - 0.1312618790102857
    - -1.172516028256826
    - 0.09935198975744082
    - 0.404822053148406
