walk:
  c_d: 1.6
  c_v: 0
  dt: 0.185607791043881
  g: -9.8
  kd:
  - 29.35805853869697
  - 38.35805853869697
  - 29.35805853869697
  - 29.35805853869697
  - 38.35805853869697
  - 29.35805853869697
  kd_torso: 254.09697376651675
  kp:
  - 293.5805853869697
  - 383.5805853869697
  - 293.5805853869697
  - 293.5805853869697
  - 383.5805853869697
  - 293.5805853869697
  kp_torso: 482.4137357959092
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.04353724705430332
    - 0.8885592195316565
    - -1.1454746354884948
    - 0.21683171355084432
    - -0.025982398790677957
    - 0.18956379336648616
    - 0.09819150083333635
  - - 0.08394207394985582
    - -1.2763151943519204
    - -0.014185452113126537
    - 0.10770692293060777
    - 0.028534519810347873
    - -0.09675106945462433
    - 0.06795328324321816
  - - -0.04353724705430332
    - -0.025982398790677957
    - 0.18956379336648616
    - 0.09819150083333635
    - 0.8885592195316565
    - -1.1454746354884948
    - 0.21683171355084432
  - - 0.08394207394985582
    - 0.028534519810347873
    - -0.09675106945462433
    - 0.06795328324321816
    - -1.2763151943519204
    - -0.014185452113126537
    - 0.10770692293060777
