walk:
  c_d: 1.6
  c_v: 0
  dt: 0.17386289730759358
  g: -9.8
  kd:
  - 31.06458502792182
  - 40.06458502792182
  - 31.06458502792182
  - 31.06458502792182
  - 40.06458502792182
  - 31.06458502792182
  kd_torso: 254.2381462082922
  kp:
  - 310.64585027921817
  - 400.64585027921817
  - 310.64585027921817
  - 310.64585027921817
  - 400.64585027921817
  - 310.64585027921817
  kp_torso: 485.3623966498227
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.028397114100604037
    - 0.8508027198237997
    - -1.059904818719162
    - 0.21321425023273563
    - -0.03875761957218332
    - 0.21256783831271445
    - 0.3114220352787864
  - - 0.08952723496901183
    - -1.3961753440198894
    - -0.29018942805790027
    - -0.06807250548460514
    - 0.014310399761650917
    - -0.2598786889181164
    - 0.0629863089413968
  - - -0.028397114100604037
    - -0.03875761957218332
    - 0.21256783831271445
    - 0.3114220352787864
    - 0.8508027198237997
    - -1.059904818719162
    - 0.21321425023273563
  - - 0.08952723496901183
    - 0.014310399761650917
    - -0.2598786889181164
    - 0.0629863089413968
    - -1.3961753440198894
    - -0.29018942805790027
    - -0.06807250548460514
