walk:
  c_d: 1.6
  c_v: 0
  dt: 0.16308119142679467
  g: -9.8
  kd:
  - 30.954865152941302
  - 39.9548651529413
  - 30.954865152941302
  - 30.954865152941302
  - 39.9548651529413
  - 30.954865152941302
  kd_torso: 258.0052903823544
  kp:
  - 309.548651529413
  - 399.548651529413
  - 309.548651529413
  - 309.548651529413
  - 399.548651529413
  - 309.548651529413
  kp_torso: 477.3383695164559
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.016906171788547898
    - 0.8343592642476361
    - -1.1913424668612045
    - 0.2193854071722921
    - -0.036387482843827826
    - 0.11463356271031701
    - 0.2115976270255981
  - - -0.013052310400233857
    - -1.2831768542295143
    - -0.19281492440445672
    - 0.08943477721861334
    - 0.07766040731341438
    - -0.15307099480884878
    - -0.01796044596822114
  - - -0.016906171788547898
    - -0.036387482843827826
    - 0.11463356271031701
    - 0.2115976270255981
    - 0.8343592642476361
    - -1.1913424668612045
    - 0.2193854071722921
  - - -0.013052310400233857
    - 0.07766040731341438
    - -0.15307099480884878
    - -0.01796044596822114
    - -1.2831768542295143
    - -0.19281492440445672
    - 0.08943477721861334
