walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2670257463175413
  g: -9.8
  kd:
  - 33.6093162463884
  - 42.6093162463884
  - 33.6093162463884
  - 33.6093162463884
  - 42.6093162463884
  - 33.6093162463884
  kd_torso: 267.86815925859617
  kp:
  - 336.093162463884
  - 426.093162463884
  - 336.093162463884
  - 336.093162463884
  - 426.093162463884
  - 336.093162463884
  kp_torso: 533.1789564810304
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.09957742592424734
    - 0.7304144562688775
    - -1.162909835946006
    - 0.12550345944453667
    - 0.056488655100096374
    - 0.2820611681355646
    - 0.62029578047854
  - - -0.04812333945006305
    - -1.376450232452932
    - -0.796269613474775
    - -0.07705459120632537
    - 0.03435984016201083
    - -0.21852015860663415
    - 0.9073688235131875
  - - 0.09957742592424734
    - 0.056488655100096374
    - 0.2820611681355646
    - 0.62029578047854
    - 0.7304144562688775
    - -1.162909835946006
    - 0.12550345944453667
  - - -0.04812333945006305
    - 0.03435984016201083
    - -0.21852015860663415
    - 0.9073688235131875
    - -1.376450232452932
    - -0.796269613474775
    - -0.07705459120632537
