walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24622605471210296
  g: -9.8
  kd:
  - 31.8264766378817
  - 40.826476637881704
  - 31.8264766378817
  - 31.8264766378817
  - 40.826476637881704
  - 31.8264766378817
  kd_torso: 223.71147587376234
  kp:
  - 318.264766378817
  - 408.264766378817
  - 318.264766378817
  - 318.264766378817
  - 408.264766378817
  - 318.264766378817
  kp_torso: 476.44682807710757
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.001065315146119029
    - 0.5543604816380434
    - -0.7896607666275692
    - 0.5096742380250772
    - -0.11907977898327862
    - 0.4570992329560777
    - -0.19700312386446253
  - - -0.3
    - -0.7176096566359818
    - -0.08570443709425121
    - 0.5397538687988108
    - 0.031154098528059268
    - 0.09534632764154341
    - 0.3661305995923141
  - - -0.001065315146119029
    - -0.11907977898327862
    - 0.4570992329560777
    - -0.19700312386446253
    - 0.5543604816380434
    - -0.7896607666275692
    - 0.5096742380250772
  - - -0.3
    - 0.031154098528059268
    - 0.09534632764154341
    - 0.3661305995923141
    - -0.7176096566359818
    - -0.08570443709425121
    - 0.5397538687988108
