walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2939487656327203
  g: -9.8
  kd:
  - 31.34932229935188
  - 40.34932229935188
  - 31.34932229935188
  - 31.34932229935188
  - 40.34932229935188
  - 31.34932229935188
  kd_torso: 226.4811568067408
  kp:
  - 313.49322299351877
  - 403.49322299351877
  - 313.49322299351877
  - 313.49322299351877
  - 403.49322299351877
  - 313.49322299351877
  kp_torso: 475.42910768660465
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03844542067393824
    - 0.5059978441288984
    - -0.8226490070236803
    - 0.5954170969262068
    - -0.07639622265181795
    - 0.5
    - -0.04635716956420583
  - - -0.21352746585801236
    - -0.6676925216779702
    - -0.04335296945966001
    - 0.5731446903543986
    - -0.0363494218207563
    - 0.02652668782051727
    - 0.5507360919101081
  - - 0.03844542067393824
    - -0.07639622265181795
    - 0.5
    - -0.04635716956420583
    - 0.5059978441288984
    - -0.8226490070236803
    - 0.5954170969262068
  - - -0.21352746585801236
    - -0.0363494218207563
    - 0.02652668782051727
    - 0.5507360919101081
    - -0.6676925216779702
    - -0.04335296945966001
    - 0.5731446903543986
