walk:
  c_d: 1.6
  c_v: 0
  dt: 0.18905246819711674
  g: -9.8
  kd:
  - 30.93976370788642
  - 39.93976370788642
  - 30.93976370788642
  - 30.93976370788642
  - 39.93976370788642
  - 30.93976370788642
  kd_torso: 256.1297224098558
  kp:
  - 309.3976370788642
  - 399.3976370788642
  - 309.3976370788642
  - 309.3976370788642
  - 399.3976370788642
  - 309.3976370788642
  kp_torso: 485.07522478704095
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.00028277286996870876
    - 0.9520303643319145
    - -1.2449280518257417
    - 0.1308904322028401
    - 0.07736855270585091
    - 0.13379978084185126
    - 0.31728816065970056
  - - -0.010825793610286773
    - -1.3333273046531702
    - -0.22717070222494584
    - 0.001269388418091849
    - -0.01875567972498644
    - -0.26257680928604743
    - 0.013564962487164971
  - - -0.00028277286996870876
    - 0.07736855270585091
    - 0.13379978084185126
    - 0.31728816065970056
    - 0.9520303643319145
    - -1.2449280518257417
    - 0.1308904322028401
  - - -0.010825793610286773
    - -0.01875567972498644
    - -0.26257680928604743
    - 0.013564962487164971
    - -1.3333273046531702
    - -0.22717070222494584
    - 0.001269388418091849
