walk:
  c_d: 1.6
  c_v: 0
  dt: 0.24614902020150004
  g: -9.8
  kd:
  - 29.048919203673137
  - 38.04891920367314
  - 29.048919203673137
  - 29.048919203673137
  - 38.04891920367314
  - 29.048919203673137
  kd_torso: 233.54747142145933
  kp:
  - 290.48919203673137
  - 380.48919203673137
  - 290.48919203673137
  - 290.48919203673137
  - 380.48919203673137
  - 290.48919203673137
  kp_torso: 480.7825221119544
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.01859080168059407
    - 0.8201255961958753
    - -1.0486215534991412
    - 0.31250975236201534
    - 0.05737193993632386
    - 0.2971872388543861
    - 0.016765719061267947
  - - -0.05194044318017704
    - -1.2503386788864468
    - -0.10598037074308038
    - 0.4380443197431537
    - 0.008752393694239254
    - 0.05278525013956937
    - 0.3712958084046765
  - - 0.01859080168059407
    - 0.05737193993632386
    - 0.2971872388543861
    - 0.016765719061267947
    - 0.8201255961958753
    - -1.0486215534991412
    - 0.31250975236201534
  - - -0.05194044318017704
    - 0.008752393694239254
    - 0.05278525013956937
    - 0.3712958084046765
    - -1.2503386788864468
    - -0.10598037074308038
    - 0.4380443197431537
