walk:
  c_d: 1.6
  c_v: 0
  dt: 0.17363522940126322
  g: -9.8
  kd:
  - 30.902096129409564
  - 39.902096129409564
  - 30.902096129409564
  - 30.902096129409564
  - 39.902096129409564
  - 30.902096129409564
  kd_torso: 253.4830251291011
  kp:
  - 309.0209612940956
  - 399.0209612940956
  - 309.0209612940956
  - 309.0209612940956
  - 399.0209612940956
  - 309.0209612940956
  kp_torso: 484.80752841993797
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.007530210115529162
    - 0.9174605479921034
    - -1.2343297196418757
    - 0.1569266050156511
    - -0.002676963671029804
    - 0.16568930109686256
    - 0.2685022111660295
  - - 0.03473208958896924
    - -1.3625616548153334
    - -0.22629806830290336
    - 0.0028871893922471914
    - -0.026466972807546982
    - -0.2623199528415109
    - 0.0655316876208919
  - - -0.007530210115529162
    - -0.002676963671029804
    - 0.16568930109686256
    - 0.2685022111660295
    - 0.9174605479921034
    - -1.2343297196418757
    - 0.1569266050156511
  - - 0.03473208958896924
    - -0.026466972807546982
    - -0.2623199528415109
    - 0.0655316876208919
    - -1.3625616548153334
    - -0.22629806830290336
    - 0.0028871893922471914
