walk:
  c_d: 1.6
  c_v: 0
  dt: 0.162393961588939
  g: -9.8
  kd:
  - 32.49317008181787
  - 41.49317008181787
  - 32.49317008181787
  - 32.49317008181787
  - 41.49317008181787
  - 32.49317008181787
  kd_torso: 264.08780544777375
  kp:
  - 324.9317008181787
  - 414.9317008181787
  - 324.9317008181787
  - 324.9317008181787
  - 414.9317008181787
  - 324.9317008181787
  kp_torso: 508.19941271595263
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.07873821637697995
    - 0.6907603750685004
    - -1.3376709224154733
    - 0.243869718208022
    - 0.06132128911205305
    - 0.33514193786833035
    - 0.3676275841024505
  - - -0.07536850475902519
    - -1.4350322423268185
    - -0.4775892271070845
    - -0.2866651345335656
    - 0.015385569544825917
    - -0.1943572277481056
    - 0.09618793808034487
  - - 0.07873821637697995
    - 0.06132128911205305
    - 0.33514193786833035
    - 0.3676275841024505
    - 0.6907603750685004
    - -1.3376709224154733
    - 0.243869718208022
  - - -0.07536850475902519
    - 0.015385569544825917
    - -0.1943572277481056
    - 0.09618793808034487
    - -1.4350322423268185
    - -0.4775892271070845
    - -0.2866651345335656
