walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1921738686268436
  g: -9.8
  kd:
  - 31.26274674649345
  - 40.26274674649345
  - 31.26274674649345
  - 31.26274674649345
  - 40.26274674649345
  - 31.26274674649345
  kd_torso: 257.1403334812014
  kp:
  - 312.62746746493445
  - 402.62746746493445
  - 312.62746746493445
  - 312.62746746493445
  - 402.62746746493445
  - 312.62746746493445
  kp_torso: 485.564438322879
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.004595948968414042
    - 0.8297639620462196
    - -1.144307980946241
    - 0.2127306279957794
    - 0.002020416730563024
    - 0.19485798424588144
    - 0.3774265281723566
  - - 0.11461251153783587
    - -1.3833789011789
    - -0.26918765854893956
    - -0.10111507354894772
    - 0.02902187272909204
    - -0.33641768784758397
    - -0.008983189804331868
  - - -0.004595948968414042
    - 0.002020416730563024
    - 0.19485798424588144
    - 0.3774265281723566
    - 0.8297639620462196
    - -1.144307980946241
    - 0.2127306279957794
  - - 0.11461251153783587
    - 0.02902187272909204
    - -0.33641768784758397
    - -0.008983189804331868
    - -1.3833789011789
    - -0.26918765854893956
    - -0.10111507354894772
