walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2454472437589207
  g: -9.8
  kd:
  - 33.32480323764072
  - 42.32480323764072
  - 33.32480323764072
  - 33.32480323764072
  - 42.32480323764072
  - 33.32480323764072
  kd_torso: 273.6237946170375
  kp:
  - 333.2480323764072
  - 423.2480323764072
  - 333.2480323764072
  - 333.2480323764072
  - 423.2480323764072
  - 333.2480323764072
  kp_torso: 527.0750377380231
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.10325229125611357
    - 0.6486969110559052
    - -1.1374277536784274
    - 0.13690236631242836
    - -0.061039187430072875
    - 0.2529099766061236
    - 0.5900486152671781
  - - 0.028207249161980627
    - -1.393837831025472
    - -0.7510684884968087
    - -0.05453918529168683
    - 0.05755635358441322
    - -0.21944026453318816
    - 0.9302437936892489
  - - 0.10325229125611357
    - -0.061039187430072875
    - 0.2529099766061236
    - 0.5900486152671781
    - 0.6486969110559052
    - -1.1374277536784274
    - 0.13690236631242836
  - - 0.028207249161980627
    - 0.05755635358441322
    - -0.21944026453318816
    - 0.9302437936892489
    - -1.393837831025472
    - -0.7510684884968087
    - -0.05453918529168683
