walk:
  c_d: 1.6
  c_v: 0
  dt: 0.18575762950668961
  g: -9.8
  kd:
  - 31.26505593208778
  - 40.26505593208778
  - 31.26505593208778
  - 31.26505593208778
  - 40.26505593208778
  - 31.26505593208778
  kd_torso: 233.576279070904
  kp:
  - 312.6505593208778
  - 402.6505593208778
  - 312.6505593208778
  - 312.6505593208778
  - 402.6505593208778
  - 312.6505593208778
  kp_torso: 479.12102672981865
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.04368733498035146
    - 0.5353061743384488
    - -0.7294326021601506
    - 0.5318910897555982
    - -0.010232449886560246
    - 0.36981958332668263
    - 0.04876757958720612
  - - -0.17981976954851567
    - -0.5329828474918167
    - -0.3122652933064272
    - 0.3560886266685118
    - -0.011194100899251758
    - 0.049283236592310584
    - 0.4922406067900901
  - - 0.04368733498035146
    - -0.010232449886560246
    - 0.36981958332668263
    - 0.04876757958720612
    - 0.5353061743384488
    - -0.7294326021601506
    - 0.5318910897555982
  - - -0.17981976954851567
    - -0.011194100899251758
    - 0.049283236592310584
    - 0.4922406067900901
    - -0.5329828474918167
    - -0.3122652933064272
    - 0.3560886266685118
