walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2961490202015
  g: -9.8
  kd:
  - 28.554129660853636
  - 37.55412966085364
  - 28.554129660853636
  - 28.554129660853636
  - 37.55412966085364
  - 28.554129660853636
  kd_torso: 232.6722320520354
  kp:
  - 285.54129660853636
  - 375.54129660853636
  - 285.54129660853636
  - 285.54129660853636
  - 375.54129660853636
  - 285.54129660853636
  kp_torso: 475.045328118322
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03389209210166518
    - 0.8441450489497758
    - -1.0302223173815965
    - 0.22412684992302612
    - -0.021864683692356172
    - 0.19669224375949493
    - 0.125068032107798
  - - -0.04808449430323289
    - -1.2759586646639238
    - -0.09174958660663879
    - 0.3367164371670598
    - -0.045883110456631314
    - -0.04161766938807374
    - 0.3879417511699061
  - - 0.03389209210166518
    - -0.021864683692356172
    - 0.19669224375949493
    - 0.125068032107798
    - 0.8441450489497758
    - -1.0302223173815965
    - 0.22412684992302612
  - - -0.04808449430323289
    - -0.045883110456631314
    - -0.04161766938807374
    - 0.3879417511699061
    - -1.2759586646639238
    - -0.09174958660663879
    - 0.3367164371670598
