walk:
  c_d: 1.6
  c_v: 0
  dt: 0.3014395904886753
  g: -9.8
  kd:
  - 27.967662739811573
  - 36.96766273981157
  - 27.967662739811573
  - 27.967662739811573
  - 36.96766273981157
  - 27.967662739811573
  kd_torso: 237.71554218166943
  kp:
  - 279.6766273981157
  - 369.6766273981157
  - 279.6766273981157
  - 279.6766273981157
  - 369.6766273981157
  - 279.6766273981157
  kp_torso: 479.2356407761339
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.03137724900488765
    - 0.9144105655673623
    - -1.106155815505751
    - 0.24828471495446666
    - -0.07077084186827094
    - 0.20664360109620286
    - 0.24337708297997465
  - - 0.028645356172123562
    - -1.3627605728979908
    - -0.08736787261393798
    - 0.21173601630813693
    - 0.03468177757435617
    - -0.04882172431754059
    - 0.29013949464165534
  - - 0.03137724900488765
    - -0.07077084186827094
    - 0.20664360109620286
    - 0.24337708297997465
    - 0.9144105655673623
    - -1.106155815505751
    - 0.24828471495446666
  - - 0.028645356172123562
    - 0.03468177757435617
    - -0.04882172431754059
    - 0.29013949464165534
    - -1.3627605728979908
    - -0.08736787261393798
    - 0.21173601630813693
