walk:
  c_d: 1.6
  c_v: 0
  dt: 0.19388375847455358
  g: -9.8
  kd:
  - 33.3958868611497
  - 42.3958868611497
  - 33.3958868611497
  - 33.3958868611497
  - 42.3958868611497
  - 33.3958868611497
  kd_torso: 266.48966586129256
  kp:
  - 333.95886861149694
  - 423.95886861149694
  - 333.95886861149694
  - 333.95886861149694
  - 423.95886861149694
  - 333.95886861149694
  kp_torso: 525.9192755496548
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.018585191122438584
    - 0.7843262316043268
    - -1.1996406979263559
    - 0.18070621698950115
    - 0.014446902933261537
    - 0.3013828003347312
    - 0.494834477831608
  - - 0.10947312231986367
    - -1.4609627534069125
    - -0.604181623540096
    - -0.3077679190842907
    - -0.01457051604484338
    - -0.33379243625989125
    - 0.4125695144921573
  - - 0.018585191122438584
    - 0.014446902933261537
    - 0.3013828003347312
    - 0.494834477831608
    - 0.7843262316043268
    - -1.1996406979263559
    - 0.18070621698950115
  - - 0.10947312231986367
    - -0.01457051604484338
    - -0.33379243625989125
    - 0.4125695144921573
    - -1.4609627534069125
    - -0.604181623540096
    - -0.3077679190842907
