walk:
  c_d: 1.6
  c_v: 0
  dt: 0.15975597521477305
  g: -9.8
  kd:
  - 32.151011286793896
  - 41.151011286793896
  - 32.151011286793896
  - 32.151011286793896
  - 41.151011286793896
  - 32.151011286793896
  kd_torso: 257.67248865756926
  kp:
  - 321.5101128679389
  - 411.5101128679389
  - 321.5101128679389
  - 321.5101128679389
  - 411.5101128679389
  - 321.5101128679389
  kp_torso: 494.3327227913878
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.02719156009862473
    - 0.9015321400859112
    - -1.1692573659997918
    - 0.21754010961825038
    - 0.045274082001269325
    - 0.19997994980754133
    - 0.2451785633519742
  - - 0.06850880439148463
    - -1.3242947987233713
    - -0.2953216028115135
    - 0.008116441468029853
    - 0.0757289126977224
    - -0.22474144101541677
    - 0.0437095396844901
  - - -0.02719156009862473
    - 0.045274082001269325
    - 0.19997994980754133
    - 0.2451785633519742
    - 0.9015321400859112
    - -1.1692573659997918
    - 0.21754010961825038
  - - 0.06850880439148463
    - 0.0757289126977224
    - -0.22474144101541677
    - 0.0437095396844901
    - -1.3242947987233713
    - -0.2953216028115135
    - 0.008116441468029853
