walk:
  c_d: 1.6
  c_v: 0
  dt: 0.1768982185919398
  g: -9.8
  kd:
  - 31.429187935949308
  - 40.42918793594931
  - 31.429187935949308
  - 31.429187935949308
  - 40.42918793594931
  - 31.429187935949308
  kd_torso: 269.3764630271571
  kp:
  - 314.29187935949307
  - 404.29187935949307
  - 314.29187935949307
  - 314.29187935949307
  - 404.29187935949307
  - 314.29187935949307
  kp_torso: 485.026703801909
  max_torque: 800
  mu: 0.65
  targets:
  - - -0.0026409566465305026
    - 0.8392572467631704
    - -1.2012782858202282
    - 0.19807607566029634
    - -0.005377345209700249
    - 0.23448626273496728
    - 0.45349766278748876
  - - 0.030125967361157226
    - -1.3622161666786161
    - -0.2788423781426445
    - -0.1820512769212473
    - 0.12236129545955696
    - -0.34566968337847753
    - -0.04801814605590481
  - - -0.0026409566465305026
    - -0.005377345209700249
    - 0.23448626273496728
    - 0.45349766278748876
    - 0.8392572467631704
    - -1.2012782858202282
    - 0.19807607566029634
  - - 0.030125967361157226
    - 0.12236129545955696
    - -0.34566968337847753
    - -0.04801814605590481
    - -1.3622161666786161
    - -0.2788423781426445
    - -0.1820512769212473
