walk:
  c_d: 1.6
  c_v: 0
  dt: 0.2807815054148531
  g: -9.8
  kd:
  - 31.47670772240233
  - 40.47670772240233
  - 31.47670772240233
  - 31.47670772240233
  - 40.47670772240233
  - 31.47670772240233
  kd_torso: 221.16067649542617
  kp:
  - 314.7670772240233
  - 404.7670772240233
  - 314.7670772240233
  - 314.7670772240233
  - 404.7670772240233
  - 314.7670772240233
  kp_torso: 483.966490091195
  max_torque: 800
  mu: 0.65
  targets:
  - - 0.015761424309724624
    - 0.4602995976432702
    - -0.7619692583103892
    - 0.45069410296657486
    - 0.02218764213994222
    - 0.4885122920374125
    - -0.14313902895169056
  - - -0.2829445395265835
    - -0.765822699541896
    - 0.015571878075788803
    - 0.4759561002031397
    - -0.004723485913495013
    - 0.1602586959971734
    - 0.4647513610494346
  - - 0.015761424309724624
    - 0.02218764213994222
    - 0.4885122920374125
    - -0.14313902895169056
    - 0.4602995976432702
    - -0.7619692583103892
    - 0.45069410296657486
  - - -0.2829445395265835
    - -0.004723485913495013
    - 0.1602586959971734
    - 0.4647513610494346
    - -0.765822699541896
    - 0.015571878075788803
    - 0.4759561002031397
